### ISSUE TITLE
Some elements don't work / color correctly | Mathematica 13

### ISSUE THREAD

**Issue by Sandwich1699975** [dracula/wolfram-notebooks#4]
The input "+" is discoloured, and the bar below previous computations is white. 

![image](https://user-images.githubusercontent.com/50229842/148746681-573beab7-4b7b-4ee1-b0c5-7552a0f8d309.png)

---

This is for Mathematica 13

**Comment by Sandwich1699975** [comment]
I understand that this may be impossible to change, so you can just close this issue if that is the case

**Comment by jldohmann** [comment]
@Sandwich1699975 unfortunately as a user I don't have control over the toolbar and other interactive UI elements and how they're displayed, but thank you for bringing it up (in case others stumble upon this)
